package com.example.info

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.platform.LocalConfiguration

object Strings {
    private val translations = mapOf(
        "zh" to mapOf(
            "app_name" to "设备信息",
            "home" to "主页",
            "environment" to "设备",
            "restart" to "重启",
            "settings" to "设置",
            "device_overview" to "设备概览",
            "android_version" to "Android 版本",
            "api_level" to "API 级别",
            "bootloader" to "Bootloader",
            "process_count" to "所有进程数",
            "mem_usage" to "内存大小",
            "selinux_status" to "SELinux 状态",
            "current_time" to "当前时间",
            "root_modules" to "Root 模块数量",
            "storage_status" to "已使用",
            "manufacturer" to "制造商",
            "battery_level" to "电池电量",
            "theme_settings" to "主题设置",
            "lang_settings" to "语言设置",
            "terminal" to "终端命令行",
            "about" to "关于与支持",
            "run" to "运行",
            "output" to "输出结果",
            "shell_hint" to "输入 shell 命令",
            "root_hint" to "提示: 默认使用 Root 权限执行命令",
            "github_title" to "GitHub 项目地址",
            "github_sub" to "查看源码、反馈建议或贡献代码",
            "web_title" to "官方网站",
            "web_sub" to "访问我们的官方网站获取更多信息",
            "jvm_version" to "JVM 版本",
            "build_date" to "构建日期",
            "model" to "型号",
            "hardware" to "硬件",
            "kernel_version" to "内核版本",
            "kernel_date" to "内核编译日期",
            "mem_brand" to "内存品牌",
            "mem_total" to "内存大小",
            "ufs_info" to "UFS 信息",
            "soc_info" to "处理器信息",
            "storage_usage" to "已使用",
            "used" to "已使用",
            "gpu_info" to "GPU 信息",
            "opengl_version" to "OpenGL ES 版本",
            "vulkan_version" to "Vulkan 版本",
            "opencl_version" to "OpenCL 支持",
            "sensor_info" to "传感器信息",
            "view_data" to "查看数据",
            "sensor_data" to "传感器实时数据",
            "close" to "关闭",
            "tab_system" to "系统",
            "tab_hardware" to "硬件",
            "tab_graphics" to "图形",
            "tab_sensors" to "传感器",
            "tab_battery" to "电池",
            "tab_apps" to "应用",
            "tab_screen" to "屏幕",
            "tab_camera" to "摄像头",
            "screen_res" to "分辨率",
            "screen_refresh" to "刷新率",
            "screen_density" to "像素密度",
            "screen_size" to "屏幕尺寸",
            "screen_xdpi" to "物理 DPI",
            "screen_features" to "支持功能",
            "screen_hdr" to "HDR 支持",
            "camera_id" to "摄像头 ID",
            "camera_facing" to "朝向",
            "camera_megapixels" to "分辨率 (MP)",
            "camera_iso" to "ISO 范围",
            "camera_focal" to "焦距",
            "camera_sensor" to "传感器尺寸",
            "camera_raw" to "RAW 支持",
            "camera_flash" to "闪光灯",
            "camera_af" to "自动对焦",
            "camera_zoom" to "缩放范围",
            "camera_stab" to "防抖支持",
            "camera_aperture" to "光圈",
            "battery_status" to "健康状态",
            "battery_tech" to "电池技术",
            "battery_capacity" to "设计容量",
            "battery_voltage" to "当前电压",
            "battery_temp" to "当前温度",
            "app_user" to "用户应用",
            "app_system" to "系统应用",
            "install_apk" to "安装 APK",
            "uninstall" to "卸载",
            "open" to "打开",
            "app_info" to "应用详情"
        ),
        "en" to mapOf(
            "app_name" to "Device Info",
            "home" to "Home",
            "environment" to "Device",
            "restart" to "Restart",
            "settings" to "Settings",
            "device_overview" to "Device Overview",
            "android_version" to "Android Version",
            "api_level" to "API Level",
            "bootloader" to "Bootloader",
            "process_count" to "Total Processes",
            "mem_usage" to "Memory Usage",
            "selinux_status" to "SELinux Status",
            "current_time" to "Current Time",
            "root_modules" to "Root Modules",
            "storage_status" to "Storage Status",
            "manufacturer" to "Manufacturer",
            "battery_level" to "Battery",
            "theme_settings" to "Theme Settings",
            "lang_settings" to "Language Settings",
            "terminal" to "Terminal",
            "about" to "About & Support",
            "run" to "Run",
            "output" to "Output",
            "shell_hint" to "Enter shell command",
            "root_hint" to "Hint: Uses Root by default",
            "github_title" to "GitHub Repository",
            "github_sub" to "View source, feedback or contribute",
            "web_title" to "Official Website",
            "web_sub" to "Visit our official website",
            "jvm_version" to "JVM Version",
            "build_date" to "Build Date",
            "model" to "Model",
            "hardware" to "Hardware",
            "kernel_version" to "Kernel Version",
            "kernel_date" to "Kernel Build Date",
            "mem_brand" to "Memory Brand",
            "mem_total" to "Memory Total",
            "ufs_info" to "UFS Info",
            "soc_info" to "Processor Info",
            "storage_usage" to "Storage Usage Rate",
            "used" to "Used",
            "gpu_info" to "GPU Info",
            "opengl_version" to "OpenGL ES Version",
            "vulkan_version" to "Vulkan Version",
            "opencl_version" to "OpenCL Support",
            "sensor_info" to "Sensor Info",
            "view_data" to "View Data",
            "sensor_data" to "Live Sensor Data",
            "close" to "Close",
            "tab_system" to "System",
            "tab_hardware" to "Hardware",
            "tab_graphics" to "Graphics",
            "tab_sensors" to "Sensors",
            "tab_battery" to "Battery",
            "tab_apps" to "Apps",
            "tab_screen" to "Screen",
            "tab_camera" to "Camera",
            "screen_res" to "Resolution",
            "screen_refresh" to "Refresh Rate",
            "screen_density" to "Density",
            "screen_size" to "Screen Size",
            "screen_hdr" to "HDR Support",
            "camera_id" to "Camera ID",
            "camera_facing" to "Facing",
            "camera_megapixels" to "Megapixels",
            "camera_iso" to "ISO Range",
            "camera_focal" to "Focal Length",
            "battery_status" to "Health Status",
            "battery_tech" to "Technology",
            "battery_capacity" to "Capacity",
            "battery_voltage" to "Voltage",
            "battery_temp" to "Temperature",
            "app_user" to "User Apps",
            "app_system" to "System Apps",
            "install_apk" to "Install APK",
            "uninstall" to "Uninstall",
            "open" to "Open",
            "app_info" to "App Details"
        )
    )

    @Composable
    @ReadOnlyComposable
    fun get(key: String): String {
        val configuration = LocalConfiguration.current
        val lang = configuration.locales[0].language
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
