package com.example.info

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.platform.LocalConfiguration

object Strings {
    private val translations = mapOf(
        "zh" to mapOf(
            "app_name" to "设备信息",
            "home" to "主页",
            "environment" to "设备",
            "restart" to "重启",
            "settings" to "设置",
            "device_overview" to "设备概览",
            "android_version" to "Android 版本",
            "api_level" to "API 级别",
            "bootloader" to "Bootloader",
            "process_count" to "所有进程数",
            "mem_usage" to "内存大小",
            "selinux_status" to "SELinux 状态",
            "current_time" to "当前时间",
            "root_modules" to "Root 模块数量",
            "storage_status" to "已使用",
            "manufacturer" to "制造商",
            "battery_level" to "电池电量",
            "theme_settings" to "主题设置",
            "lang_settings" to "语言设置",
            "terminal" to "终端命令行",
            "about" to "关于与支持",
            "run" to "运行",
            "output" to "输出结果",
            "shell_hint" to "输入 shell 命令",
            "root_hint" to "提示: 默认使用 Root 权限执行命令",
            "github_title" to "GitHub 项目地址",
            "github_sub" to "查看源码、反馈建议或贡献代码",
            "web_title" to "官方网站",
            "web_sub" to "访问我们的官方网站获取更多信息",
            "jvm_version" to "JVM 版本",
            "build_date" to "构建日期",
            "model" to "型号",
            "hardware" to "硬件",
            "kernel_version" to "内核版本",
            "kernel_date" to "内核编译日期",
            "mem_brand" to "内存品牌",
            "mem_total" to "内存大小",
            "ufs_info" to "UFS 信息",
            "soc_info" to "处理器信息",
            "storage_usage" to "已使用",
            "used" to "已使用",
            "gpu_info" to "GPU 信息",
            "opengl_version" to "OpenGL ES 版本",
            "vulkan_version" to "Vulkan 版本",
            "opencl_version" to "OpenCL 支持",
            "sensor_info" to "传感器信息",
            "view_data" to "查看数据",
            "sensor_data" to "传感器实时数据",
            "close" to "关闭",
            "tab_system" to "系统",
            "tab_hardware" to "硬件",
            "tab_graphics" to "图形",
            "tab_sensors" to "传感器",
            "tab_battery" to "电池",
            "tab_apps" to "应用",
            "tab_partitions" to "分区",
            "tab_screen" to "屏幕",
            "tab_camera" to "摄像头",
            "hdr_test" to "HDR 图片效果检查",
            "hdr_test_desc" to "显示高动态范围颜色以检查屏幕 HDR 性能",
            "camera_preview" to "摄像头预览",
            "temp_sensors" to "温度传感器",
            "no_temp_sensors" to "未检测到温度传感器",
            "tab_processor" to "处理器",
            "processor_control" to "CPU/GPU 设定",
            "core_count" to "核心数量",
            "single_core_settings" to "单核设置",
            "core_settings_note" to "注：如果您使用了第三方调度，则此功能会自动失效。很少有手机支持单核设置，故只需任意修改某核心即可改变全局核心/某组核心。因处理器限制，频率只能向某频率尽可能靠近，无法锁频。请先将工作模式切换为 userspace。",
            "cpu_governor" to "CPU 工作模式",
            "cpu_min_freq" to "最低 CPU 频率",
            "cpu_max_freq" to "最高 CPU 频率",
            "cpu_freq_range" to "支持频率范围",
            "cpu_lock_freq" to "CPU 锁频",
            "not_set" to "未设置锁频",
            "corectl_switch" to "低性能模式",
            "corectl_desc" to "使用 corectl 开启低性能模式以节省电量",
            "screen_res" to "分辨率",
            "screen_refresh" to "刷新率",
            "screen_density" to "像素密度",
            "screen_size" to "屏幕尺寸",
            "screen_xdpi" to "物理 DPI",
            "screen_features" to "支持功能",
            "screen_hdr" to "HDR 支持",
            "change_res" to "修改分辨率",
            "change_dpi" to "修改 DPI",
            "change_refresh" to "修改刷新率",
            "reset" to "重置",
            "apply" to "应用",
            "camera_id" to "摄像头 ID",
            "camera_facing" to "朝向",
            "camera_megapixels" to "分辨率 (MP)",
            "camera_iso" to "ISO 范围",
            "camera_focal" to "焦距",
            "camera_sensor" to "传感器尺寸",
            "camera_raw" to "RAW 支持",
            "camera_flash" to "闪光灯",
            "camera_af" to "自动对焦",
            "camera_zoom" to "缩放范围",
            "camera_stab" to "防抖支持",
            "camera_aperture" to "光圈",
            "battery_status" to "健康状态",
            "battery_tech" to "电池技术",
            "battery_capacity" to "设计容量",
            "battery_voltage" to "当前电压",
            "battery_temp" to "当前温度",
            "app_user" to "用户应用",
            "app_system" to "系统应用",
            "install_apk" to "安装 APK",
            "uninstall" to "卸载",
            "open" to "打开",
            "app_info" to "应用详情",
            "flash" to "刷入",
            "export" to "导出",
            "partition_name" to "分区名称",
            "partition_size" to "分区大小",
            "partition_path" to "设备节点",
            "select_image" to "选择镜像文件",
            "export_success" to "导出成功",
            "flash_success" to "刷入成功",
            "operation_failed" to "操作失败",
            "confirm_flash" to "确认刷入？此操作极具风险！",
            "confirm_export" to "确认导出分区镜像？",
            "tab_broadcast" to "数据广播",
            "start_broadcast" to "开始广播",
            "stop_broadcast" to "停止广播",
            "discovered_devices" to "发现的设备",
            "no_devices" to "暂未发现设备",
            "broadcast_active" to "广播正在运行",
            "broadcast_inactive" to "广播已停止",
            "broadcast_settings" to "广播设置",
            "port" to "端口",
            "target_ip" to "目标 IP (可选)",
            "broadcast_desc" to "设置 IP 和端口进行局域网数据同步",
            "gpu_renderer" to "GPU 渲染器",
            "gpu_vendor" to "GPU 供应商",
            "wifi_info" to "Wi-Fi 详细信息",
            "bt_info" to "蓝牙详细信息",
            "audio_info" to "音频详细信息"
        ),
        "en" to mapOf(
            "app_name" to "Device Info",
            "home" to "Home",
            "environment" to "Device",
            "restart" to "Restart",
            "settings" to "Settings",
            "device_overview" to "Device Overview",
            "android_version" to "Android Version",
            "api_level" to "API Level",
            "bootloader" to "Bootloader",
            "process_count" to "Total Processes",
            "mem_usage" to "Memory Usage",
            "selinux_status" to "SELinux Status",
            "current_time" to "Current Time",
            "root_modules" to "Root Modules",
            "storage_status" to "Storage Status",
            "manufacturer" to "Manufacturer",
            "battery_level" to "Battery",
            "theme_settings" to "Theme Settings",
            "lang_settings" to "Language Settings",
            "terminal" to "Terminal",
            "about" to "About & Support",
            "run" to "Run",
            "output" to "Output",
            "shell_hint" to "Enter shell command",
            "root_hint" to "Hint: Uses Root by default",
            "github_title" to "GitHub Repository",
            "github_sub" to "View source, feedback or contribute",
            "web_title" to "Official Website",
            "web_sub" to "Visit our official website",
            "jvm_version" to "JVM Version",
            "build_date" to "Build Date",
            "model" to "Model",
            "hardware" to "Hardware",
            "kernel_version" to "Kernel Version",
            "kernel_date" to "Kernel Build Date",
            "mem_brand" to "Memory Brand",
            "mem_total" to "Memory Total",
            "ufs_info" to "UFS Info",
            "soc_info" to "Processor Info",
            "storage_usage" to "Storage Usage Rate",
            "used" to "Used",
            "gpu_info" to "GPU Info",
            "opengl_version" to "OpenGL ES Version",
            "vulkan_version" to "Vulkan Version",
            "opencl_version" to "OpenCL Support",
            "sensor_info" to "Sensor Info",
            "view_data" to "View Data",
            "sensor_data" to "Live Sensor Data",
            "close" to "Close",
            "tab_system" to "System",
            "tab_hardware" to "Hardware",
            "tab_graphics" to "Graphics",
            "tab_sensors" to "Sensors",
            "tab_battery" to "Battery",
            "tab_apps" to "Apps",
            "tab_partitions" to "Partitions",
            "tab_screen" to "Screen",
            "tab_camera" to "Camera",
            "hdr_test" to "HDR Image Effect Check",
            "hdr_test_desc" to "Display high dynamic range colors to check screen HDR performance",
            "camera_preview" to "Camera Preview",
            "temp_sensors" to "Temperature Sensors",
            "no_temp_sensors" to "No temperature sensors detected",
            "tab_processor" to "Processor",
            "processor_control" to "CPU/GPU Settings",
            "core_count" to "Core Count",
            "single_core_settings" to "Single Core Settings",
            "core_settings_note" to "Note: If you use a third-party scheduler, this function will automatically fail. Very few phones support single-core settings, so just modifying any core can change the global/group cores. Due to processor limitations, frequencies can only be as close as possible to a certain frequency, and cannot be locked. Please switch the working mode to userspace first.",
            "cpu_governor" to "CPU Governor",
            "cpu_min_freq" to "Min CPU Frequency",
            "cpu_max_freq" to "Max CPU Frequency",
            "cpu_freq_range" to "Supported Frequency Range",
            "cpu_lock_freq" to "CPU Lock Frequency",
            "not_set" to "Not Set",
            "corectl_switch" to "Low Power Mode",
            "corectl_desc" to "Use corectl to enable low power mode for power saving",
            "screen_res" to "Resolution",
            "screen_refresh" to "Refresh Rate",
            "change_res" to "Change Resolution",
            "change_dpi" to "Change DPI",
            "change_refresh" to "Change Refresh Rate",
            "reset" to "Reset",
            "apply" to "Apply",
            "screen_density" to "Density",
            "screen_size" to "Screen Size",
            "screen_hdr" to "HDR Support",
            "camera_id" to "Camera ID",
            "camera_facing" to "Facing",
            "camera_megapixels" to "Megapixels",
            "camera_iso" to "ISO Range",
            "camera_focal" to "Focal Length",
            "battery_status" to "Health Status",
            "battery_tech" to "Technology",
            "battery_capacity" to "Capacity",
            "battery_voltage" to "Voltage",
            "battery_temp" to "Temperature",
            "app_user" to "User Apps",
            "app_system" to "System Apps",
            "install_apk" to "Install APK",
            "uninstall" to "Uninstall",
            "open" to "Open",
            "app_info" to "App Details",
            "flash" to "Flash",
            "export" to "Export",
            "partition_name" to "Name",
            "partition_size" to "Size",
            "partition_path" to "Path",
            "select_image" to "Select Image File",
            "export_success" to "Export Successful",
            "flash_success" to "Flash Successful",
            "operation_failed" to "Operation Failed",
            "confirm_flash" to "Confirm Flash? This is highly risky!",
            "confirm_export" to "Confirm Export partition image?",
            "tab_broadcast" to "Data Broadcast",
            "start_broadcast" to "Start Broadcast",
            "stop_broadcast" to "Stop Broadcast",
            "discovered_devices" to "Discovered Devices",
            "no_devices" to "No devices discovered",
            "broadcast_active" to "Broadcasting...",
            "broadcast_inactive" to "Broadcast Stopped",
            "broadcast_settings" to "Broadcast Settings",
            "port" to "Port",
            "target_ip" to "Target IP (Optional)",
            "broadcast_desc" to "Set IP and Port for LAN synchronization",
            "gpu_renderer" to "GPU Renderer",
            "gpu_vendor" to "GPU Vendor",
            "wifi_info" to "Wi-Fi Details",
            "bt_info" to "Bluetooth Details",
            "audio_info" to "Audio Details"
        )
    )

    @Composable
    @ReadOnlyComposable
    fun get(key: String): String {
        val configuration = LocalConfiguration.current
        val lang = configuration.locales[0].language
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
