package com.example.info

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.platform.LocalConfiguration

object Strings {
    private val translations = mapOf(
        "zh" to mapOf(
            "app_name" to "设备信息",
            "home" to "主页",
            "environment" to "设备",
            "restart" to "重启",
            "settings" to "设置",
            "device_overview" to "设备概览",
            "android_version" to "Android 版本",
            "api_level" to "API 级别",
            "bootloader" to "Bootloader",
            "process_count" to "所有进程数",
            "mem_usage" to "内存使用率",
            "selinux_status" to "SELinux 状态",
            "current_time" to "当前时间",
            "root_modules" to "Root 模块数量",
            "storage_status" to "存储状态",
            "manufacturer" to "制造商",
            "battery_level" to "电池电量",
            "theme_settings" to "主题设置",
            "lang_settings" to "语言设置",
            "terminal" to "终端命令行",
            "about" to "关于与支持",
            "run" to "运行",
            "output" to "输出结果",
            "shell_hint" to "输入 shell 命令",
            "root_hint" to "提示: 默认使用 Root 权限执行命令",
            "github_title" to "GitHub 项目地址",
            "github_sub" to "查看源码、反馈建议或贡献代码",
            "web_title" to "官方网站",
            "web_sub" to "访问我们的官方网站获取更多信息",
            "jvm_version" to "JVM 版本",
            "build_date" to "构建日期",
            "model" to "型号",
            "hardware" to "硬件",
            "kernel_version" to "内核版本",
            "kernel_date" to "内核编译日期",
            "mem_brand" to "内存品牌",
            "mem_total" to "内存大小",
            "ufs_info" to "UFS 信息",
            "soc_info" to "处理器信息",
            "storage_usage" to "存储使用率"
        ),
        "en" to mapOf(
            "app_name" to "Device Info",
            "home" to "Home",
            "environment" to "Device",
            "restart" to "Restart",
            "settings" to "Settings",
            "device_overview" to "Device Overview",
            "android_version" to "Android Version",
            "api_level" to "API Level",
            "bootloader" to "Bootloader",
            "process_count" to "Total Processes",
            "mem_usage" to "Memory Usage",
            "selinux_status" to "SELinux Status",
            "current_time" to "Current Time",
            "root_modules" to "Root Modules",
            "storage_status" to "Storage Status",
            "manufacturer" to "Manufacturer",
            "battery_level" to "Battery",
            "theme_settings" to "Theme Settings",
            "lang_settings" to "Language Settings",
            "terminal" to "Terminal",
            "about" to "About & Support",
            "run" to "Run",
            "output" to "Output",
            "shell_hint" to "Enter shell command",
            "root_hint" to "Hint: Uses Root by default",
            "github_title" to "GitHub Repository",
            "github_sub" to "View source, feedback or contribute",
            "web_title" to "Official Website",
            "web_sub" to "Visit our official website",
            "jvm_version" to "JVM Version",
            "build_date" to "Build Date",
            "model" to "Model",
            "hardware" to "Hardware",
            "kernel_version" to "Kernel Version",
            "kernel_date" to "Kernel Build Date",
            "mem_brand" to "Memory Brand",
            "mem_total" to "Memory Total",
            "ufs_info" to "UFS Info",
            "soc_info" to "Processor Info",
            "storage_usage" to "Storage Usage Rate"
        ),
        "ja" to mapOf(
            "app_name" to "デバイス情報",
            "home" to "ホーム",
            "environment" to "デバイス",
            "restart" to "再起動",
            "settings" to "設定",
            "device_overview" to "デバイスの概要",
            "android_version" to "Android バージョン",
            "api_level" to "API レベル",
            "bootloader" to "ブートローダー",
            "process_count" to "総プロセス数",
            "mem_usage" to "メモリ使用率",
            "selinux_status" to "SELinux ステータス",
            "current_time" to "現在時刻",
            "root_modules" to "Root モジュール数",
            "storage_status" to "ストレージ状態",
            "manufacturer" to "メーカー",
            "battery_level" to "バッテリー残量",
            "theme_settings" to "テーマ設定",
            "lang_settings" to "言語設定",
            "terminal" to "ターミナル",
            "about" to "バージョンとサポート",
            "run" to "実行",
            "output" to "出力結果",
            "shell_hint" to "シェルコマンドを入力",
            "root_hint" to "ヒント: デフォルトで Root 権限を使用",
            "github_title" to "GitHub リポジトリ",
            "github_sub" to "ソースの表示、フィードバック、貢献",
            "web_title" to "公式サイト",
            "web_sub" to "詳細については公式サイトをご覧ください",
            "jvm_version" to "JVM バージョン",
            "build_date" to "ビルド日",
            "model" to "モデル",
            "hardware" to "ハードウェア",
            "kernel_version" to "カーネルバージョン",
            "kernel_date" to "カーネルビルド日",
            "mem_brand" to "メモリブランド",
            "mem_total" to "メモリ合計",
            "ufs_info" to "UFS 情報",
            "soc_info" to "プロセッサ情報",
            "storage_usage" to "ストレージ使用率"
        ),
        "ru" to mapOf(
            "app_name" to "Инфо об устройстве",
            "home" to "Главная",
            "environment" to "Устройство",
            "restart" to "Перезагрузка",
            "settings" to "Настройки",
            "device_overview" to "Обзор устройства",
            "android_version" to "Версия Android",
            "api_level" to "Уровень API",
            "bootloader" to "Загрузчик",
            "process_count" to "Всего процессов",
            "mem_usage" to "Использование памяти",
            "selinux_status" to "Статус SELinux",
            "current_time" to "Текущее время",
            "root_modules" to "Root модули",
            "storage_status" to "Память",
            "manufacturer" to "Производитель",
            "battery_level" to "Заряд батареи",
            "theme_settings" to "Тема оформления",
            "lang_settings" to "Язык",
            "terminal" to "Терминал",
            "about" to "О программе",
            "run" to "Запуск",
            "output" to "Результат",
            "shell_hint" to "Введите shell команду",
            "root_hint" to "Подсказка: По умолчанию используется Root",
            "github_title" to "GitHub проект",
            "github_sub" to "Исходный код и поддержка",
            "web_title" to "Официальный сайт",
            "web_sub" to "Посетите наш сайт",
            "jvm_version" to "Версия JVM",
            "build_date" to "Дата сборки",
            "model" to "Модель",
            "hardware" to "Железо",
            "kernel_version" to "Версия ядра",
            "kernel_date" to "Дата сборки ядра",
            "mem_brand" to "Бренд памяти",
            "mem_total" to "Объем памяти",
            "ufs_info" to "UFS Инфо",
            "soc_info" to "Процессор",
            "storage_usage" to "Использование хранилища"
        )
    )

    @Composable
    @ReadOnlyComposable
    fun get(key: String): String {
        val configuration = LocalConfiguration.current
        val lang = configuration.locales[0].language
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
